apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-cart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DevOpsShoppingCart/DevConf.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz-argo-cd
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
